### ISSUE TITLE
Licence for the images

### ISSUE THREAD

**Issue by hgwood** [kunklejr/nodejs-explained-pres#1]
The graphics in your presentation are great: good looking and time-less. Would they be available for re-use ? Under which terms ? What about commercial re-use ?

**Comment by kunklejr** [comment]
Feel free to use them as you see fit. Please just attribute the source to me. License is http://creativecommons.org/licenses/by/4.0/ http://creativecommons.org/licenses/by/4.0/

Thanks,
Jeff

**Comment by hgwood** [comment]
Thank you.
